#!/usr/bin/expect
set timeout 30
spawn ssh admin@172.28.140.99
expect "admin@172.28.140.99's password:" 
send "0okm(IJN\r"
sleep 0.2
send "source wangjincheng/.bash_profile\r"
sleep 0.2
send "cd\r"
interact
