#!/usr/bin/expect
set timeout 30
spawn ssh admin@172.28.140.99
expect "admin@XXX.28.XXX.99's password:" 
send "0XXXX\r"
sleep 0.2
send "source wangjincheng/.bash_profile\r"
sleep 0.2
send "cd\r"
interact
