#!/bin/bash
for i in {1..5}
do
   echo "Welcome $i times"
done


function get_sku_id_in_each_day {
    SAVE_PATH=$2
    hadoop fs -test -e $SAVE_PATH
    if [ $? -eq 0 ];then
         hadoop fs -rmr ${SAVE_PATH}
    fi
    hadoop fs -mkdir ${SAVE_PATH}
    for i in {0..-1}
    do
        j=$[-1*${i}]
        day=`date -d "${i} days ago" +%Y-%m-%d`
        if [ $i -lt 10 ]; then
            sku_input="/user/part-0000${j}"
            sku_output="/user/${day}"
            echo ${sku_input}
            echo ${sku_output}
        fi
        hadoop fs -mkdir ${sku_output}
        hadoop fs -cp ${sku_input} ${sku_output}
    done
}
   

[root@showsky ~]# date -d "4 days ago" +%Y%m%d
20100103
上面是四天前的日期
[root@showsky ~]# date -d "-1 days ago" +%Y%m%d
20100108
上面是一天后的日期


comments:
:<<\EOF
your code here
EOF
